version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./:/app

  turn:
    image: coturn/coturn:4.6
    container_name: coturn
    command: ["/bin/sh", "-c", "ARGS=''; if [ -n \"$TURN_EXTERNAL_IP\" ]; then ARGS=\"-E $TURN_EXTERNAL_IP\"; fi; exec /usr/bin/turnserver -c /etc/turnserver.conf $ARGS"]
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49160-49200:49160-49200/udp"
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
    environment:
      - TURN_EXTERNAL_IP=${TURN_EXTERNAL_IP}
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - "8080:8080"

volumes:
  pgdata:
